//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourcecodeReviewone.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISourceCodeService")]
    public interface ISourceCodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeSelect", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeSelectResponse")]
        System.Data.DataSet SourceCodeSelect(string flag, string PageVal, string parval1, string parval2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeSelect", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeSelectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SourceCodeSelectAsync(string flag, string PageVal, string parval1, string parval2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeConfirm", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeConfirmResponse")]
        string SourceCodeConfirm(string flag, string PageVal, string parval1, string parval2, string parval3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeConfirm", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeConfirmResponse")]
        System.Threading.Tasks.Task<string> SourceCodeConfirmAsync(string flag, string PageVal, string parval1, string parval2, string parval3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeDocUpload", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeDocUploadResponse")]
        string SourceCodeDocUpload(string flag, string Param, byte[] upload_file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISourceCodeService/SourceCodeDocUpload", ReplyAction="http://tempuri.org/ISourceCodeService/SourceCodeDocUploadResponse")]
        System.Threading.Tasks.Task<string> SourceCodeDocUploadAsync(string flag, string Param, byte[] upload_file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISourceCodeServiceChannel : SourcecodeReviewone.ServiceReference1.ISourceCodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SourceCodeServiceClient : System.ServiceModel.ClientBase<SourcecodeReviewone.ServiceReference1.ISourceCodeService>, SourcecodeReviewone.ServiceReference1.ISourceCodeService {
        
        public SourceCodeServiceClient() {
        }
        
        public SourceCodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SourceCodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SourceCodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SourceCodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet SourceCodeSelect(string flag, string PageVal, string parval1, string parval2) {
            return base.Channel.SourceCodeSelect(flag, PageVal, parval1, parval2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SourceCodeSelectAsync(string flag, string PageVal, string parval1, string parval2) {
            return base.Channel.SourceCodeSelectAsync(flag, PageVal, parval1, parval2);
        }
        
        public string SourceCodeConfirm(string flag, string PageVal, string parval1, string parval2, string parval3) {
            return base.Channel.SourceCodeConfirm(flag, PageVal, parval1, parval2, parval3);
        }
        
        public System.Threading.Tasks.Task<string> SourceCodeConfirmAsync(string flag, string PageVal, string parval1, string parval2, string parval3) {
            return base.Channel.SourceCodeConfirmAsync(flag, PageVal, parval1, parval2, parval3);
        }
        
        public string SourceCodeDocUpload(string flag, string Param, byte[] upload_file) {
            return base.Channel.SourceCodeDocUpload(flag, Param, upload_file);
        }
        
        public System.Threading.Tasks.Task<string> SourceCodeDocUploadAsync(string flag, string Param, byte[] upload_file) {
            return base.Channel.SourceCodeDocUploadAsync(flag, Param, upload_file);
        }
    }
}
